#!/bin/bash
if [[ ! "$( echo $PATH | grep '/usr/local/bin' )" ]]; then export PATH=$PATH:/usr/local/bin; fi
LBF="/usr/local/lib/faron_falcon"; . $LBF/colors; . $LBF/functions;
#################### BEGIN
echo $Fno "no"
FMGS="YES"
echo $FGmsg"


exit 0
