#!/bin/bash
startgrn=`date +%s`

sudo apt-get dist-upgrade
sudo apt-get autoremove
sudo apt-get autoclean
sudo apt-get clean
sudo apt-get update

stopred=`date +%s`; faronruntime=$(( $stopred - $startgrn )); echo "$0 | $startgrn | $stopred | $faronruntime " >> ~/.falcon/logs/scripts.log; exit 0

