#!/bin/bash

PREFILE="$1"
DocVideo="<!DOCTYPE html>
<html lang=\"en\">
    <head>
        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">
        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\">
        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
        <meta name=\"description\" content=\"\">
        <meta name=\"author\" content=\"faron\">
        <title>$PREFILE</title>
        <link rel=\"stylesheet\" href=\"./.jsc/css/cssengine.css\" />
        <link rel=\"stylesheet\" href=\"./.jsc/css/mediaelement/mediaelementplayer.min.css\" />
		<link rel=\"stylesheet\" href=\"./.jsc/css/mediaelement/mejs-skins.css\" /> 
		 <style>
 		 html { height: 100%; width: 100%; } body { min-width: 100% ; min-height:  100%; background: black;
 		} video { min-height: 100%; min-width: 800px; }
		</style> 
	</head>
    <body>
        <video align=\"center\" class=\"mejs-skins\" id=\"$PREFILE\" controls muted poster=\"https://tv.faron.ca/.priv/thumbs/$PREFILE.png\"> 
	        <source src=\"https://tv.faron.ca/.priv/$PREFILE.mp4\" type=\"video/mp4\"> 
        </video>
        <script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script>
        <script src=\"./.jsc/js/appengine.js\"></script>
        <script src=\"./.jsc/js/mediaelement/mediaelement-and-player.min.js\"></script> 
        <script>
        $( document ).ready(function(){
	        $('audio,video').mediaelementplayer({
    	        defaultVideoHeight: 480,
        	    startLanguage: 'en',
            	stretching: 'auto'
	        });
	    });
        </script>
    </body>
</html>" > "$PREFILE.html"



exit 0