#!/bin/bash
startgrn=`date +%s`

sudo apt-get build-dep $1
sudo apt-get install $1


stopred=`date +%s`; faronruntime=$(( $stopred - $startgrn )); echo "$0 | $startgrn | $stopred | $faronruntime " >> ~/.falcon/logs/scripts.log; exit 0
