/***************************************
 * AUTO-GENERATED FILE, DO NOT EDIT!!! *
 * Generated by: tools/config.py       *
 ***************************************/

/* Platform */
#define PLATFORM amd64
#define PLATFORM_amd64

/* CPU type */
#define PROCESSOR opteron
#define PROCESSOR_opteron

/* RAM disk format */
#define RDFMT ext4fs
#define RDFMT_ext4fs

/* Kernel architecture */
#define KARCH amd64
#define KARCH_amd64

/* User space architecture */
#define UARCH amd64
#define UARCH_amd64

/* Boot architecture */
#define BARCH amd64
#define BARCH_amd64

/* Compiler */
#define COMPILER clang
#define COMPILER_clang

/* Fences */
#define CONFIG_FENCES_P4

/* IOMAP bitmap support */
#define CONFIG_IOMAP_BITMAP

/* ACPI support */
#define CONFIG_ACPI

/* Hierarchical page tables support */
#define CONFIG_PAGE_PT

/* Multiboot standard support */
#define CONFIG_MULTIBOOT

/* FPU support */
#define CONFIG_FPU

/* Support for SMP */
#define CONFIG_SMP

/* Debug build */
#define CONFIG_DEBUG

/* Deadlock detection support for spinlocks */
#define CONFIG_DEBUG_SPINLOCK

/* Lazy FPU context switching */
#define CONFIG_FPU_LAZY

/* Support for userspace debuggers */
#define CONFIG_UDEBUG

/* Kernel console support */
#define CONFIG_KCONSOLE

/* Kernel symbol information */
#define CONFIG_SYMTAB

/* Detailed kernel logging */
#define CONFIG_LOG

/* Kernel function tracing */
#define CONFIG_TRACE

/* Compile kernel tests */
#define CONFIG_TEST

/* Input device class */
#define CONFIG_HID_IN generic
#define CONFIG_HID_IN_generic

/* Output device class */
#define CONFIG_HID_OUT generic
#define CONFIG_HID_OUT_generic

/* PC keyboard support */
#define CONFIG_PC_KBD

/* Support for i8042 controller */
#define CONFIG_I8042

/* EGA support */
#define CONFIG_EGA

/* Framebuffer support */
#define CONFIG_FB

/* Default framebuffer mode */
#define CONFIG_BFB_MODE 1280x800
#define CONFIG_BFB_MODE_1280x800

/* Default framebuffer depth */
#define CONFIG_BFB_BPP 24
#define CONFIG_BFB_BPP_24

/* Write core files */
#define CONFIG_WRITE_CORE_FILES

/* Include development files (headers, libraries) */
#define CONFIG_DEVEL_FILES

/* Strip binaries */
#define CONFIG_STRIP_BINARIES

/* Optimize for size */
#define CONFIG_OPTIMIZE_FOR_SIZE

/* Barebone build with essential binaries only */
#define CONFIG_BAREBONE

/* Start virtual USB host controller */
#define CONFIG_RUN_VIRTUAL_USB_HC

/* OHCI root hub port power switching */
#define OHCI_POWER_SWITCH no
#define OHCI_POWER_SWITCH_no

/* GRUB boot loader architecture */
#define GRUB_ARCH pc
#define GRUB_ARCH_pc

/* Default framebuffer width */
#define CONFIG_BFB_WIDTH 1280
#define CONFIG_BFB_WIDTH_1280

/* Default framebuffer height */
#define CONFIG_BFB_HEIGHT 800
#define CONFIG_BFB_HEIGHT_800

#define REVISION unknown (unknown)
#define TIMESTAMP_UNIX 1434491812
#define TIMESTAMP 2015-06-16 17:56:52
