alias	falcon=" cd $HOME/.falcon/scripts "
alias 	ff.clean=" ff.bin.files.backup.delete "
alias 	ff.cloud=" cd /home/www/cloud/html "
alias 	ff.code=" cd $HOME/.falcon/code "
alias 	ff.edit.alias=" nano $HOME/.bash_aliases "
alias 	ff.edit.bashrc=" nano $HOME/.bashrc "
alias 	ff.edit.scripts=" nano $HOME/.bash_scripts "
alias 	ff.fstab=" cat /etc/fstab "
alias 	ff.id="   cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 "
alias 	ff.java=" cd $HOME/.falcon/code/javas/projects "
alias 	ff.loc=" cd /home/root/usr/local "
alias 	ff.log=" tail -n 50 /var/log/syslog "
alias 	ff.md5="      grabfiles=( \"$( find -L $PWD -maxdepth 1 -type f ! -type d ! -path '*/.gvfs' -exec basename {} \; )\" ); for w in \"${grabfiles[@]}\"; do md5sum $w; done "
alias 	ff.node="    cd $HOME/.falcon/code/node/projects-node "
alias 	ff.open=" nautilus . "
alias 	ff.script="  cd $HOME/.falcon/scripts "
alias 	ff.vid="  cd $HOME/Videos"
alias 	ff6=" ssh -o PubkeyAuthentication=no faron@192.168.1.6 "
alias 	ff7=" ssh -o PubkeyAuthentication=no faron@192.168.1.7 "
alias 	ffmet=" cd $HOME/.falcon/scripts/meteor/projects-meteor "
alias 	ffprivs=" cd /srv/www/html/.jsc/privs "
alias 	fly=" cd $HOME/.falcon "
alias 	libr=" cd /srv/www/faronintel/htdocs/.jsc/.lib/libraries "
alias 	mtrmake=" meteor-kitchen "
alias 	play="mplayer -msgcolor -msgmodule"
alias 	ports="     sudo netstat -tulanp "
alias 	ff.work=" cd /srv/www/faronintel/htdocs/.jsc/projects "
alias 	setup="     cd $HOME/.falcon/setup "
alias   bashsr="    cd $HOME/ && source $HOME/.bashrc "
alias   bin="       cd $HOME/.bin "
alias   diskspace=" gksu baobab "
alias   ff.colors="  cat $HOME/.falcon/bash/.bash_colors_help "
alias   ff.desk="    cd $HOME/Desktop 2>/dev/null"
alias   ff.dl="      cd $HOME/Downloads 2>/dev/null"
alias   ff.pix="     cd $HOME/Pictures 2>/dev/null "
alias   ff.vid="     cd $HOME/Videos 2>/dev/null"
alias   ff10="      ssh -o PubkeyAuthentication=no faron@192.168.1.10 "
alias   ff2="      ssh -o PubkeyAuthentication=no faron@192.168.1.2 "
alias   fff="       cd /srv/www/htdocs "
alias   ff.html="    cd $HOME/.falcon/code/htmls/projects-htmls "
alias   ff.x="     cd $HOME/Videos/XXX "
alias   }}="        cat "
alias   ff.tdl=" cd $HOME/media/torrents"
alias   ff.tp="cd $HOME/media/torrents-tbp"
