alias	falcon=" cd ~/.falcon/scripts/falcon-fly "
alias 	ff.clean=" ff.bin.files.backup.delete "
alias 	ff.cloud=" cd /home/www/cloud/html "
alias 	ff.code=" cd ~/.falcon/scripts "
alias 	ff.edit.alias=" nano ~/.falcon/bash/.bash_aliases "
alias 	ff.edit.bashrc=" nano ~/.falcon/bash/.bashrc "
alias 	ff.edit.profile=" nano ~/.falcon/bash/.profile "
alias 	ff.edit.scripts=" nano ~/.falcon/bash/.bash_scripts "
alias 	ff.fstab=" cat /etc/fstab "
alias 	ff.home="  cd /home "
alias 	ff.id="   cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 "
alias 	ff.java=" cd ~/.falcon/scripts/Scripts/javas/projects "
alias 	ff.loc=" cd /home/local "
alias 	ff.log=" tail -n 50 /var/log/syslog "
alias 	ff.md5="      grabfiles=( \"$(find $PWD -maxdepth 1 -type f -exec basename {} \; )\" ); for w in \"${grabfiles[@]}\"; do md5sum $w; done "
alias 	ff.node="    cd ~/.falcon/scripts/node/projects-node "
alias 	ff.open=" nautilus .  "
alias 	ff.script="  cd ~/.falcon/scripts/Scripts "
alias 	ff.vid="  cd ~/Videos"
alias 	ff6=" ssh -o PubkeyAuthentication=no faron@192.168.1.6 "
alias 	ffmet=" cd ~/.falcon/scripts/meteor/projects-meteor "
alias 	ffprivs=" cd /var/www/html/.jsc/privs "
alias 	fly=" cd ~/.falcon "
alias 	libr=" cd /var/www/html/.jsc/.lib/libraries "
alias 	mtrmake=" meteor-kitchen "
alias 	play="mplayer -msgcolor -msgmodule"
alias 	ports="     sudo netstat -tulanp "
alias 	proj=" cd /var/www/html/.jsc/projects "
alias 	setup="     cd ~/.falcon/setup/stable "
alias   bashsr="    cd ~/ && source ~/.profile "
alias   bin="       cd ~/.bin "
alias   diskspace=" gksu baobab "
alias   ff.colors="  cat ~/.falcon/bash/.bash_colors_help "
alias   ff.desk="    cd ~/Desktop "
alias   ff.dl="      cd ~/Downloads "
alias   ff.pix="     cd ~/Pictures "
alias   ff.vid="     cd ~/Videos "
alias   ff10="      ssh -o PubkeyAuthentication=no faron@192.168.1.10 "
alias   ff2="      ssh -o PubkeyAuthentication=no faron@192.168.1.2 "
alias   fff="       cd /srv/www/htdocs "
alias   ffhtml="    cd ~/.falcon/scripts/Scripts/htmls/projects "
alias   ffxxx="     cd ~/Videos/XXX "
alias   }}="        cat "