alias   bashsr="    cd /home/faron && source /home/faron/.bashrc "
alias   bin="       cd /home/faron/.bin "
alias   }}="        cat "
alias   diskspace=" gksu baobab "
alias	falcon=" cd /home/faron/.falcon/scripting/falcon-fly "
alias   ff10="      ssh -o PubkeyAuthentication=no faron@192.168.1.10 "
alias   ff2="      ssh -o PubkeyAuthentication=no faron@192.168.1.2 "
alias 	ff6=" ssh -o PubkeyAuthentication=no faron@192.168.1.6 "
alias 	ffals-edit=" nano /home/faron/.falcon/bash/.bash_aliases "
alias 	ffbash-edit=" nano /home/faron/.falcon/bash/.bashrc "
alias 	ffclips="  cd /home/faron/Videos"
alias   ffcolors="  cat ~/.falcon/bash/.bash_colors_help "
alias   ffdesk="    cd /home/faron/Desktop "
alias   ffdl="      cd /home/faron/Downloads "
alias   fff="       cd /home/www/html "
alias   ffhtml="    cd /home/faron/Scripts/htmls/projects "
alias 	ffjava=" cd /home/faron/Scripts/javas/projects "
alias 	ffloc=" cd /home/local "
alias 	ffmd5="      grabfiles=( \"$(find $PWD -maxdepth 1 -type f -exec basename {} \; )\" ); for w in \"${grabfiles[@]}\"; do md5sum $w; done "
alias 	ffmet=" cd /home/faron/Scripts/meteor/projects-meteor "
alias 	ffnode="    cd /home/faron/Scripts/node/projects-node "
alias 	ffopen=" nautilus .  "
alias   ffpix="     cd /home/faron/Pictures "
alias 	ffprofile-edit=" nano /home/faron/.falcon/bash/.profile "
alias 	ffroot="  cd /home "
alias 	ffscr-edit=" nano /home/faron/.falcon/bash/.bash_scripts "
alias 	ffscript="  cd /home/faron/Scripts "
alias 	ffstream=" cd /home/faron/Streamings/files "
alias 	ffuid="   cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 "
alias   ffvid="     cd /home/faron/Videos "
alias   ffxxx="     cd /home/faron/Videos/XXX "
alias   home="      cd /home/faron "
alias 	mp4=" cd /home/faron/Streamings/files/engine/factory-mp4/output"
alias 	mtrmake=" meteor-kitchen "
alias 	ports="     sudo netstat -tulanp "
alias 	setup="     cd /home/faron/.falcon/setup/stable "
alias 	proj=" cd /var/www/html/.jsc/projects "
alias 	libr=" cd /var/www/html/.jsc/.lib/libraries "
alias 	play="mplayer -msgcolor -msgmodule"
alias 	ffruby=" cd /home/faron/Scripts/ruby/projects "
alias 	ffprivs=" cd /var/www/html/.jsc/privs "
alias 	fly=" cd /home/faron/.falcon "
alias 	ffcloud=" cd /home/www/cloud/html "
alias 	ff.node.global=" cd /home/local/lib/node_modules "
alias 	ffclean=" ff.bin.files.backup.delete "
alias 	ffstab=" cat /etc/fstab "
alias 	ffcode=" cd /home/faron/.falcon/scripts "
alias 	fflog=" tail -n 50 /var/log/syslog "

